import { apiUrl } from "@/lib/api-origin";
import {
  isAllowedMimeType,
  MAX_ATTACHMENT_BYTES,
  MAX_PREVIEW_TEXT_BYTES,
} from "@/lib/attachment-limits";

/**
 * The client half of `/api/attachments/*` (EI-242) — the ONE place in the app
 * that moves file bytes.
 *
 * Same two conventions as `lib/email-ingest.ts`, for the same reasons:
 * `credentials: "include"` because the route authenticates against Better
 * Auth's session cookie and local dev is genuinely cross-origin, and
 * `apiUrl()` rather than a bare relative path because `next dev` (:3000) runs
 * no Worker at all.
 *
 * ## Online-only, on purpose (v1)
 *
 * There is no offline queue here. Local-first normally means a write lands in
 * Dexie and syncs later, but a file is not a JSON patch and the outbox only
 * carries patches — an offline attach would need blob bytes in Dexie, a
 * second queue, and a per-attachment state machine. That is deferred work,
 * not an oversight (`docs/ATTACHMENTS.md` §"What v1 leaves out").
 *
 * The visible consequence, which the UI must state rather than let someone
 * discover: **offline you can neither attach a file nor open one** whose
 * bytes this device has not already fetched.
 */

/** Re-exported so the sheet has one import, and so the numbers it renders are
 * provably the ones the Worker enforces. */
export {
  ALLOWED_MIME_TYPES,
  formatBytes,
  MAX_ATTACHMENT_BYTES,
  MAX_PREVIEW_CSV_ROWS,
  MAX_PREVIEW_TEXT_BYTES,
  maxAttachmentMb,
  type PreviewKind,
  previewKindFor,
} from "@/lib/attachment-limits";

/**
 * A refusal the user can act on — wrong file type, too big, signed out,
 * offline. Distinct from a genuine failure so the UI can show the message
 * verbatim instead of "something went wrong".
 */
export class AttachmentError extends Error {
  constructor(
    message: string,
    readonly code: string,
  ) {
    super(message);
    this.name = "AttachmentError";
  }
}

/** What `POST /api/attachments` returns. The caller writes the row from it. */
export interface UploadedAttachment {
  id: string;
  todoId: string;
  filename: string;
  mimeType: string;
  byteSize: number;
  storageKey: string;
}

/** Server rejection code -> what a person should read. */
const MESSAGE_BY_CODE: Record<string, string> = {
  "too-large": "That file is too large.",
  "unsupported-type": "That file type is not supported.",
  "content-mismatch": "That file's contents don't match its type.",
  empty: "That file is empty.",
  "missing-filename": "That file has no name.",
};

/**
 * Uploads the bytes and returns what the row should say.
 *
 * **This does not write the row.** The caller does, through `mutate()`, so
 * the metadata rides the ordinary outbox like every other entity. Bytes
 * first, row second — a row must never reference an object that is not
 * there. See `createAttachment` in `store/repositories.ts`.
 *
 * `attachmentId` is generated by the caller (`newId()`) so the id in the R2
 * key and the id on the row are the same value.
 *
 * Raw body rather than `FormData`: the Worker reads `request.arrayBuffer()`
 * directly, which is one less parse on each end. The filename travels
 * percent-encoded in `X-Filename` because a header cannot hold arbitrary
 * UTF-8.
 */
export async function uploadAttachment(
  file: File,
  todoId: string,
  attachmentId: string,
): Promise<UploadedAttachment> {
  // Checked here as well as on the server so the common mistakes cost no
  // upload at all. The server is still the enforcement — this is courtesy.
  if (file.size === 0) throw new AttachmentError("That file is empty.", "empty");
  if (!isAllowedMimeType(file.type.split(";")[0].trim().toLowerCase())) {
    throw new AttachmentError("That file type is not supported.", "unsupported-type");
  }
  // Deliberately the STANDARD cap, not the owner's: the client cannot know
  // whether this session is the owner without asking, and a rejected 5-25 MB
  // upload from the owner is a worse trade than one wasted round trip. The
  // server allows it; this pre-check only skips obviously hopeless files.
  if (file.size > MAX_ATTACHMENT_BYTES * 5) {
    throw new AttachmentError("That file is too large.", "too-large");
  }

  const query = new URLSearchParams({ todoId, id: attachmentId });
  let response: Response;
  try {
    response = await fetch(apiUrl(`/api/attachments?${query}`), {
      method: "POST",
      credentials: "include",
      headers: {
        "Content-Type": file.type,
        "X-Filename": encodeURIComponent(file.name),
      },
      body: file,
    });
  } catch {
    // `fetch` rejects rather than resolving when there is no network at all.
    throw new AttachmentError("You're offline — attachments need a connection.", "offline");
  }

  if (response.status === 401) {
    throw new AttachmentError("Sign in to attach files.", "unauthenticated");
  }
  if (!response.ok) {
    const body = (await response.json().catch(() => ({}))) as { error?: string };
    const code = body.error ?? "unknown";
    throw new AttachmentError(MESSAGE_BY_CODE[code] ?? "That file could not be attached.", code);
  }
  return response.json();
}

/**
 * Where to point an `<img>` or a download link.
 *
 * A plain URL, not a fetched blob: the browser's own cache then handles
 * repeat views, and the response is marked `private, immutable` for exactly
 * that. The route is session-authenticated, so this only resolves for the
 * signed-in owner.
 */
export function attachmentUrl(attachmentId: string): string {
  return apiUrl(`/api/attachments/${encodeURIComponent(attachmentId)}`);
}

/**
 * The same object, asked for in a form the browser will RENDER rather than
 * download.
 *
 * Only meaningful for PDF today: images already come back `inline` so the
 * plain URL is enough, and text/CSV are fetched as text and drawn by us. The
 * flag widens the `Content-Disposition` the server picks and makes it attach
 * `Content-Security-Policy: sandbox`; it grants no extra access, and
 * ownership is checked identically either way.
 */
export function attachmentPreviewUrl(attachmentId: string): string {
  return `${attachmentUrl(attachmentId)}?preview=1`;
}

/**
 * Reads an attachment as TEXT for the preview dialog.
 *
 * Capped at `MAX_PREVIEW_TEXT_BYTES` — a 25 MB CSV is a legal upload, and
 * putting it in the DOM would hang the tab. `truncated` is returned rather
 * than hidden so the dialog can say so instead of silently showing a
 * fraction of the file.
 *
 * Decoded non-fatally: the bytes already passed strict UTF-8 validation at
 * upload, but a cut at `MAX_PREVIEW_TEXT_BYTES` can land mid-codepoint, and
 * one replacement character at the very end beats throwing away the preview.
 */
export async function fetchAttachmentText(
  attachmentId: string,
): Promise<{ text: string; truncated: boolean }> {
  // `?raw=1` — the app origin streams these bytes itself rather than
  // redirecting to the user-content origin. This is the one read we parse
  // ourselves, so it needs no isolation, and keeping it same-origin avoids
  // a credentialed cross-origin fetch (see `handleRawDownload`).
  const response = await fetch(`${attachmentUrl(attachmentId)}?raw=1`, {
    credentials: "include",
  });
  if (!response.ok) throw new AttachmentError("That file could not be read.", "unreadable");

  const buffer = await response.arrayBuffer();
  const truncated = buffer.byteLength > MAX_PREVIEW_TEXT_BYTES;
  const slice = truncated ? buffer.slice(0, MAX_PREVIEW_TEXT_BYTES) : buffer;
  return { text: new TextDecoder().decode(slice), truncated };
}

/**
 * Deletes the BYTES. The row is tombstoned separately by the caller.
 *
 * Idempotent, and deliberately forgiving: a failure here leaves an orphaned
 * object, which costs storage and breaks nothing, so it must never block the
 * user's delete. See `deleteAttachment` in `store/repositories.ts` for the
 * ordering.
 */
export async function deleteAttachmentBytes(attachmentId: string): Promise<void> {
  await fetch(apiUrl(`/api/attachments/${encodeURIComponent(attachmentId)}`), {
    method: "DELETE",
    credentials: "include",
  });
}
