import { defineConfig } from "drizzle-kit";

/**
 * Global/D1 tables only — todo data lives in the per-user Durable Object.
 *
 * `auth-schema.ts` is generated by `@better-auth/cli generate` and is
 * overwritten on every `npm run auth:schema`, so anything hand-written has to
 * live in its own file and be listed here instead. Both still generate into
 * `drizzle/auth/`, which is what `wrangler d1 migrations apply AUTH_DB`
 * reads (see `wrangler.jsonc`'s `migrations_dir`).
 */
export default defineConfig({
  dialect: "sqlite",
  driver: "d1-http",
  schema: ["./src/server/auth-schema.ts", "./src/server/email/schema.ts"],
  out: "./drizzle/auth",
});
