import { defineConfig } from "drizzle-kit";

/**
 * Auth tables only (user, session, account, verification) — todo data lives in
 * the per-user Durable Object, not D1. Schema is generated by
 * `@better-auth/cli generate`, not hand-written; this file only points
 * drizzle-kit at it for SQL migration generation.
 */
export default defineConfig({
  dialect: "sqlite",
  driver: "d1-http",
  schema: "./src/server/auth-schema.ts",
  out: "./drizzle/auth",
});
